### ISSUE TITLE
[Bug] unknown stat `shield%`

### ISSUE THREAD

**Issue by soleilvermeil** [eikofee/eikonomiya-front#10]
**Describe the bug**
The effect of 4pc of Tenacity of the Millelith (supposedly `shield%` according to [the data repo](https://github.com/eikofee/eikonomiya-data/blob/master/artefacts.yml)) is showing "unknown" instead of "Shield%". This also affects the "Basic Stats" pannel.

**Screenshots**
![temp](https://github.com/eikofee/eikonomiya-front/assets/100100316/6cecf9dc-e6b6-4637-8f91-395c62a2685f)

**Comment by eikofee** [comment]
fixed in 593bb3210daa4eeb03822707003391d37d595ffc.
