### ISSUE TITLE
[Bug] Yet another UID causing troubles

### ISSUE THREAD

**Issue by soleilvermeil** [eikofee/eikonomiya-front#11]
**Describe the bug**
Similarly to https://github.com/eikofee/eikonomiya-front/issues/8 and https://github.com/eikofee/eikonomiya-front/issues/9, when I try to access informations of certain UIDs, there is an error instead. But since the error seems to be different and be thrown from a different place (again), I report this issue separately. When trying to access `702405924`, I get:
```
TypeError: Cannot read properties of undefined (reading 'length')
    at i.buildEnkaCharacterData (/app/.next/server/chunks/667.js:1:2735)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async i.loadPlayerData (/app/.next/server/chunks/667.js:1:5005)
    at async R.loadPlayerData (/app/.next/server/chunks/667.js:1:14217)
    at async s (/app/.next/server/app/[uid]/page.js:1:2213)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '825510610'
}
```

**To Reproduce**
1. Try to access `http://localhost:3000/702405924`

**Additional context**
This specific UID also generates errors on another tool making requests to Enka.

**Comment by eikofee** [comment]
fixed in d69d1bfaeec9d5e0492c9fb2658562b11e48ecad.
The source of the issue was their Kaeya's 2* artefact with no substats.
