### ISSUE TITLE
[Bug] Squashy portraits during selection

### ISSUE THREAD

**Issue by soleilvermeil** [eikofee/eikonomiya-front#12]
**Describe the bug**
When the screen becomes too narrow, characters' portraits start to be deformed.

**Screenshots**
![image](https://github.com/eikofee/eikonomiya-front/assets/100100316/80d5752a-d605-495e-b163-3d46afd71c4d)

**Additional context**
This seems to be related to the space taken by the characters' names, since characters such as 
Sangonomiya Kokomi are more strongy affected by this issue. This issue also seems to affect pages like `http://localhost:3000/<uid>/Sangonomiya%20Kokomi`, but only for absurdly narrow screens (e.g. for screens of <200 px wide for Kokomi).

**Comment by eikofee** [comment]
"fixed" in b9ac1a12cf752111a67ecf0125a9834ea9af1a28.
