### ISSUE TITLE
[Bug] No portrait for Yanfei

### ISSUE THREAD

**Issue by soleilvermeil** [eikofee/eikonomiya-front#13]
**Describe the bug**
Yanfei's "front" portrait is not showing up (see screenshots).

**Expected behavior**

**Screenshots**
![image](https://github.com/eikofee/eikonomiya-front/assets/100100316/24bafac6-86b7-4e2c-bd9a-c9da0e1280d2)
![image](https://github.com/eikofee/eikonomiya-front/assets/100100316/24650726-f011-4680-a898-3b0610c6ece4)

**Additional context**
In the HTML, the `src` attribute of the image has no value associated to it. In the character selection screen:
```html
<img class="aspect-square h-full" src="" alt="">
```
On Yanfei's page:
```html
<img alt="" class="aspect-square h-full" src="">
```

**Comment by eikofee** [comment]
fixed in 5e91930.
