### ISSUE TITLE
[Bug] No icon for Prayer Of Wisdom crown

### ISSUE THREAD

**Issue by soleilvermeil** [eikofee/eikonomiya-front#17]
**Describe the bug**
There seems to be no icon for the crown of the Prayer of Wisdom "set" (and probably also for the other Prayers sets, but I have not checked).

**Screenshots**
On Eikonomiya:
![image](https://github.com/eikofee/eikonomiya/assets/100100316/2b253ca6-5906-4c98-9486-4befe86a9139)

On Enka:
![image](https://github.com/eikofee/eikonomiya/assets/100100316/780aff84-afda-4691-995b-c394a67043c3)

**Comment by eikofee** [comment]
i recommend changing this artefact by another to fix it and improve in-game performances

**Comment by soleilvermeil** [comment]
> i recommend changing this artefact by another to fix it and improve in-game performances

It's not mine but thanks for the advice lol

**Comment by eikofee** [comment]
should be fixed in 7a322dd2062846d2f45ad83cf726539a32145229. Not tested though.

**Comment by soleilvermeil** [comment]
> should be fixed in [7a322dd](https://github.com/eikofee/eikonomiya/commit/7a322dd2062846d2f45ad83cf726539a32145229). Not tested though.

I confirm that it works now!
