### ISSUE TITLE
No portrait for Raiden Shogun

### ISSUE THREAD

**Issue by soleilvermeil** [eikofee/eikonomiya-front#2]
### The issue

Raiden Shogun has no portrait image.

### How to reproduce the issue

Simply go on the character selection screen (e.g. `http://localhost:3000/123456789`) or on her page (e.g. `http://localhost:3000/123456789/Raiden%20Shogun`).

**Comment by eikofee** [comment]
fixed in 0eff989 .
will be deployed in v0.2.
