### ISSUE TITLE
[Bug] "can't create directory 'data': File exists"

### ISSUE THREAD

**Issue by soleilvermeil** [eikofee/eikonomiya-front#6]
**Describe the bug**
When building the Docker image myself and a folder named `data` already exist in the same folder as `Dockerfile`, I get the following error:
```
 => ERROR [builder 4/5] RUN mkdir data                                                                             0.2s
------
 > [builder 4/5] RUN mkdir data:
0.202 mkdir: can't create directory 'data': File exists
------
Dockerfile:29
--------------------
  27 |     # Uncomment the following line in case you want to disable telemetry during the build.
  28 |     ENV NEXT_TELEMETRY_DISABLED 1
  29 | >>> RUN mkdir data
  30 |     RUN yarn build
  31 |
--------------------
ERROR: failed to solve: process "/bin/sh -c mkdir data" did not complete successfully: exit code: 1
```

**To Reproduce**
1. Create a folder `data` inside `eikonomiya-front`
2. Run `docker build -t eikonomiya-font .`

**Expected behavior**
I expected the image to be built regardless of the existence of that folder. I did create it here for convenience (thus keeping the same sort of workflow as in [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) and similar).

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by eikofee** [comment]
should be fixed with 6461a7ee6f33.
local build uses folder `_data` while docker build uses `data`.
Ideally folders should be created only if needed but I don't want data folder to be copied into docker image when building locally.
