### ISSUE TITLE
[Bug] "TypeError: Cannot read properties of undefined (reading '1')"

### ISSUE THREAD

**Issue by soleilvermeil** [eikofee/eikonomiya-front#8]
**Describe the bug**
When I try to access informations of certain UIDs, there is an error instead. For example, when trying to access `719970581`, I get:
```
TypeError: Cannot read properties of undefined (reading '1')
    at f.parseEffect (/app/.next/server/chunks/667.js:1:11846)
    at f.getArtefactEffects (/app/.next/server/chunks/667.js:1:14004)
    at async f.loadPlayerData (/app/.next/server/chunks/667.js:1:16266)
    at async s (/app/.next/server/app/[uid]/page.js:1:2213)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3372515171'
}
```

**To Reproduce**
1. Try to access `http://localhost:3000/719970581`

**Additional context**
The list of non working UIDs is of course not exhaustive, but they don't work on my side. Note that Enka returns for all of these a valid `avatarInfoList` field. In fact, I suspect the application to strugle with non-ASCII characters for the nicknames (or signature, with other tests that I did as for `700482758`)

**Comment by eikofee** [comment]
Same as #9 , it was a bug on data-side, not the image, fixed.
Navia assets will be added shortly.
