### ISSUE TITLE
[Bug] "TypeError: Cannot read properties of undefined (reading 'length')"

### ISSUE THREAD

**Issue by soleilvermeil** [eikofee/eikonomiya-front#9]
**Describe the bug**
Similarly to https://github.com/eikofee/eikonomiya-front/issues/8, when I try to access informations of certain UIDs, there is an error instead. But since the error seems to be different and be thrown from a different place, I report this issue separately. When trying to access `704207445`, I get:
```
TypeError: Cannot read properties of undefined (reading 'length')
    at f.parseEffect (/app/.next/server/chunks/667.js:1:10130)
    at f.getWeaponEffects (/app/.next/server/chunks/667.js:1:13275)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async f.loadPlayerData (/app/.next/server/chunks/667.js:1:16301)
    at async s (/app/.next/server/app/[uid]/page.js:1:2213)
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3653815343'
}
```

**To Reproduce**
1. Try to access `http://localhost:3000/704207445`

**Additional context**
The list of non working UIDs is of course not exhaustive, but they don't work on my side. Note that Enka returns for all of these a valid `avatarInfoList` field. In fact, I suspect the application either to not handle properly the avatar of the player. Indeed, on some working UIDs, it is stored as this:
```json
{
    "playerInfo": {
        "profilePicture": {
            "id": 7400
        }
    ...
}
```
While on the UID I listed above, the structure is different:
```json
{
    "playerInfo": {
        "profilePicture": {
            "avatarId": 10000015,
            "costumeId": 201501
        }
    ...
}
```

**Comment by eikofee** [comment]
Mostly fixed on data side.
Assets in the profile are bugged though but should be fixed with 02b0033 and 873ade7 and upcoming fix.
